UefiTestingPkg: Fix memory info database dump (#925)
## Description

Fixes: https://github.com/microsoft/mu_plus/issues/924

Memory info is stored in `mMemoryInfoDatabaseBuffer`. The code first
calculates how large of a buffer is needed. A "dry run" is performed to
compute that. It calls each dump handler with `AllowAllocation=FALSE`,
to get the size of the data that would be written.

However, the call to `LoadedImageTableDump()` during this phase, sets
`AllowAllocation=TRUE`. `mMemoryInfoDatabaseOffset` is still `NULL`,
then `AppendMemoryInfoDatabase()` sees that and allocates a buffer.

Now, `mMemoryInfoDatabaseSize` is advanced. Other dump handlers after
write to the buffer now that it exists.

Eventually, `DumpPagingInfo()` allocates the real (intended) buffer.
Because of what happened earlier, the "accidental" buffer is leaked and
`mMemoryInfoDatabaseSize` is non-zero which causes
`mMemoryInfoDatabaseBuffer[mMemoryInfoDatabaseSize]` to write past the
beginning of the buffer:

```c
  // Copy the new string to the end of the buffer and update the size.
  if (!EFI_ERROR (Status)) {
    CopyMem (&mMemoryInfoDatabaseBuffer[mMemoryInfoDatabaseSize], DatabaseString, NewStringSize);
    mMemoryInfoDatabaseSize = NewDatabaseSize;
  }
```

This change sets `AllowAllocation=FALSE` in that call and resets
`mMemoryInfoDatabaseSize` to zero before the real allocation as a
precaution.

- [x] Impacts functionality?
- [ ] Impacts security?
- [ ] Breaking change?
- [ ] Includes tests?
- [ ] Includes documentation?

## How This Was Tested

1. Before - Reproduce the problem

    ```
(venv) paging>python PagingReportGenerator.py -i ..\collection_data -o
report1.html
    Traceback (most recent call last):
      File "paging\PagingReportGenerator.py", line 312, in <module>
        retcode = main()
      File "paging\PagingReportGenerator.py", line 294, in main
        spt.Parse()
        ~~~~~~~~~^^
      File "paging\PagingReportGenerator.py", line 79, in Parse
        self.MemoryRangeInfo.extend(ParseInfoFile(info))
                                    ~~~~~~~~~~~~~^^^^^^
      File "paging\BinaryParsing.py", line 38, in ParseInfoFile
        MemoryRanges.append(MemoryRange(row[0], *row[1:]))
                            ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
      File "paging\MemoryRangeObjects.py", line 126, in __init__
        raise RuntimeError("Unknown type '%s' found!" % self.RecordType)
    RuntimeError: Unknown type 'MemoryMap' found!
    ```

2. After - Verify the problem no longer exists

    ```
python Windows\PagingReportGenerator.py -i ../collection_data -o
report1.html
    ```

## Integration Instructions

- N/A

Signed-off-by: Michael Kubacki <michael.kubacki@microsoft.com>